#!/usr/bin/env python3
"""Run the robot-InstrumentAutomation suites; output goes to results/.

    python run.py                 # run every suite in suites/
    python run.py configure_scpi  # run one suite by name

Robot's HTML report/log land in results/; each suite writes its captured SCPI to
results/scpi/. No hardware needed - the SCPI is generated by the Instrument_Automation
library and captured, not sent.
"""

from __future__ import annotations

import sys
from pathlib import Path

import robot

_HERE = Path(__file__).resolve().parent


def main(argv: list[str]) -> int:
    (_HERE / "results" / "scpi").mkdir(parents=True, exist_ok=True)
    suites = _HERE / "suites"
    targets = ([str((suites / a).with_suffix(".robot")) for a in argv]
               if argv else [str(suites)])
    return robot.run(
        *targets,
        outputdir=str(_HERE / "results"),
        pythonpath=[str(_HERE / "libraries")],
        loglevel="INFO",
        consolewidth=100,
    )


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
